main: com.gubertmc.MazeGeneratorPlugin
name: genmaze
api-version: 1.13
version: 1
commands:
  maze:
    description: generates a maze
    usage: /maze
  test:
    description: test command
    usage: /test