main: com.gubertmc.MazeGeneratorPlugin
name: genmaze
api-version: 1.13
version: 1
commands:
  astar:
    description: creates a maze solvable by A*
    usage: /astar
  bfs:
    description: creates a maze solvable by BFS
    usage: /bfs
  test:
    description: test command
    usage: /test