main: com.gubertmc.MazeGeneratorPlugin
name: genmaze
api-version: 1.13
version: 1
commands:
  astar:
    description: creates a maze
    usage: /astar
  test:
    description: test command
    usage: /test